<?= $block->getTemplatesHtml() ?>

<script id="custom-option-base-template" type="text/x-magento-template">
    <div class="fieldset-wrapper admin__collapsible-block-wrapper opened" id="option_<%- data.id %>">
        <div class="fieldset-wrapper-title">
            <strong
                class="admin__collapsible-title"
                data-toggle="collapse"
                data-target="#<%- data.id %>-content">
                <span id="option_<%- data.id %>_header_title"><%- data.title %></span>
            </strong>
            <div class="actions">
                <button type="button" title="<?= __('Delete Custom Option') ?>" class="action-delete" id="<?= $block->getFieldId() ?>_<%- data.id %>_delete">
                    <span><?= __('Delete Custom Option') ?></span>
                </button>
            </div>
            <div id="<?= $block->getFieldId() ?>_<%- data.id %>_move" data-role="draggable-handle" class="draggable-handle"
                 title="<?= __('Sort Custom Options') ?>"></div>
        </div>
        <div class="fieldset-wrapper-content in collapse" id="<%- data.id %>-content">
            <fieldset class="fieldset">
                <fieldset class="fieldset-alt" id="<?= $block->getFieldId() ?>_<%- data.id %>">
                    <input id="<?= $block->getFieldId() ?>_<%- data.id %>_is_delete" name="<?= $block->getFieldName() ?>[<%- data.id %>][is_delete]" type="hidden" value=""/>
                    <input id="<?= $block->getFieldId() ?>_<%- data.id %>_previous_type" name="<?= $block->getFieldName() ?>[<%- data.id %>][previous_type]" type="hidden" value="<%- data.type %>"/>
                    <input id="<?= $block->getFieldId() ?>_<%- data.id %>_previous_group" name="<?=  $block->getFieldName() ?>[<%- data.id %>][previous_group]" type="hidden" value=""/>
                    <input id="<?= $block->getFieldId() ?>_<%- data.id %>_id" name="<?= $block->getFieldName() ?>[<%- data.id %>][id]" type="hidden" value="<%- data.id %>"/>
                    <input id="<?= $block->getFieldId() ?>_<%- data.id %>_option_id" name="<?= $block->getFieldName() ?>[<%- data.id %>][option_id]" type="hidden" value="<%- data.option_id %>"/>
                    <input name="<?= $block->getFieldName() ?>[<%- data.id %>][sort_order]" type="hidden" value="<%- data.sort_order %>"/>

                    <div class="field field-option-title required">
                        <label class="label" for="<?= $block->getFieldId() ?>_<%- data.id %>_title">
                            <?= __('Option Title') ?>
                        </label>
                        <div class="control">
                            <input id="<?= $block->getFieldId() ?>_<%- data.id %>_title"
                                   name="<?=  $block->getFieldName() ?>[<%- data.id %>][title]"
                                   class="required-entry input-text"
                                   type="text"
                                   value="<%- data.title %>"
                                   data-store-label="<%- data.title %>"
                            <% if (typeof data.scopeTitleDisabled != 'undefined' && data.scopeTitleDisabled != null) { %> disabled="disabled" <% } %>
                            >
                            <%- data.checkboxScopeTitle %>
                        </div>
                    </div>

                    <div class="field field-option-input-type required">
                        <label class="label" for="<?= $block->getFieldId() ?>_<%- data.id %>_title">
                            <?= __('Input Type') ?>
                        </label>
                        <div class="control opt-type">
                            <?= $block->getTypeSelectHtml() ?>
                        </div>
                    </div>

                    <div class="field field-option-req">
                        <div class="control">
                            <input id="<?= $block->getFieldId() ?>_<%- data.id %>_required" class="is-required" type="checkbox" checked="checked"/>
                            <label for="field-option-req">
                                <?= __('Required') ?>
                            </label>
                            <span style="display:none"><?= $block->getRequireSelectHtml() ?></span>
                        </div>
                    </div>
                </fieldset>
            </fieldset>
        </div>
    </div>
</script>

<div id="import-container" style="display: none;"></div>
<?php if (!$block->isReadonly()): ?>
    <div><input type="hidden" name="affect_product_custom_options" value="1"/></div>
<?php endif; ?>
<script>
    require([
        "jquery",
        "Magento_Catalog/js/custom-options"
    ], function(jQuery){

        jQuery(function ($) {
            var fieldSet = $('[data-block=product-custom-options]');
            fieldSet.customOptions(<?php echo $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode(
                [
                    'fieldId' => $block->getFieldId(),
                    'productGridUrl' => $block->getProductGridUrl(),
                    'formKey' => $block->getFormKey(),
                    'customOptionsUrl' => $block->getCustomOptionsUrl(),
                    'isReadonly' => $block->isReadonly(),
                    'itemCount' => $block->getItemCount(),
                    'currentProductId' => $block->getCurrentProductId(),
                ]
            )?>);
            //adding data to templates
            <?php foreach ($block->getOptionValues() as $_value): ?>
            fieldSet.customOptions('addOption', <?= $_value->toJson() ?>);
            <?php endforeach; ?>
        });

    });
</script>