<?php
namespace Smart\OSC\Controller\Adminhtml\Option;

use Magento\Backend\App\Action;
use Magento\Framework\Controller\ResultFactory;

class Upload extends \Magento\Backend\App\Action
{
    public $imageUploader;

    public function __construct(
        Action\Context $context,
        \Smart\OSC\Model\ImageUploader $imageUploader
    )
    {
        parent::__construct($context);
        $this->imageUploader = $imageUploader;
    }

    public function _isAllowed()
    {
        return parent::_isAllowed(); // TODO: Change the autogenerated stub
    }

    protected function _prepareLayout()
    {
        return parent::_prepareLayout();
    }

    public function execute()
    {
        //echo '<pre>'; print_r($_FILES['product']['name']['options']);
        try {
            $post = $this->getRequest()->getParams();
//            echo '<pre>'; print_r($post['param_name']); die();
            $result = $this->imageUploader->saveFileToTmpDir($post['param_name']);
//            $this->imageUploader->moveFileFromTmp($result['name']);
            $result['cookie'] = [
                'name' => $this->_getSession()->getName(),
                'value' => $this->_getSession()->getSessionId(),
                'lifetime' => $this->_getSession()->getCookieLifetime(),
                'path' => $this->_getSession()->getCookiePath(),
                'domain' => $this->_getSession()->getCookieDomain(),
            ];

        } catch (\Exception $e) {
            $result = ['error' => $e->getMessage(), 'errorcode' => $e->getCode()];
        }
        return $this->resultFactory->create(ResultFactory::TYPE_JSON)->setData($result);
    }
}