<?php
/**
 * Created by PhpStorm.
 * User: dzung
 * Date: 25/06/2018
 * Time: 16:44
 */

namespace Smart\OSC\Model;
use Smart\OSC\Model\ResourceModel\Option\Collection;

use Magento\Store\Model\StoreManagerInterface;

class DataProvider extends \Magento\Ui\DataProvider\AbstractDataProvider
{
    public function __construct($name, $primaryFieldName, $requestFieldName, Collection $testCollection, array $meta = [], array $data = [])
    {
        $this->collection = $testCollection->create();
        parent::__construct($name, $primaryFieldName, $requestFieldName, $meta, $data);
    }

    public function getData()
    {
        $items = $this->collection->getItems();

        //Replace icon with fileuploader field name
        foreach ($items as $model) {
            $this->loadedData[$model->getId()] = $model->getData();
            if ($model->getIcon()) {
                $m['icon'][0]['name'] = $model->getIcon();
                $m['icon'][0]['url'] = $model->getIcon();
                $fullData = $this->loadedData;
                $this->loadedData[$model->getId()] = array_merge($fullData[$model->getId()], $m);
            }
        }

        return $this->loadedData;
        //return parent::getData(); // TODO: Change the autogenerated stub
    }

}