<?php
/**
 * Created by PhpStorm.
 * User: dzung
 * Date: 13/06/2018
 * Time: 17:06
 */

namespace Excellence\Hello\Model;
use Excellence\Hello\Model\ResourceModel\Test\Collection;

class DataProvider extends \Magento\Ui\DataProvider\AbstractDataProvider
{
    public function __construct($name, $primaryFieldName, $requestFieldName, Collection $testCollection, array $meta = [], array $data = [])
    {
        $this->collection = $testCollection->create();
        parent::__construct($name, $primaryFieldName, $requestFieldName, $meta, $data);
    }

    public function getData()
    {
        return [];
        //return parent::getData(); // TODO: Change the autogenerated stub
    }
}